// Self-hosts the MediaPipe vision runtime + BlazeFace models so the app never
// depends on a third-party CDN at runtime. Runs on postinstall.
import { mkdir, writeFile, stat, cp } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const pub = path.join(root, 'public')

const MODELS = [
  ['blaze_face_short_range.tflite', 'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite'],
  ['blaze_face_full_range.tflite', 'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_full_range/float16/1/blaze_face_full_range.tflite'],
]

async function size(p) {
  try {
    return (await stat(p)).size
  } catch {
    return 0
  }
}

async function copyWasm() {
  const src = path.join(root, 'node_modules/@mediapipe/tasks-vision/wasm')
  const dest = path.join(pub, 'mediapipe/wasm')
  // SIMD only. Every browser released since 2023 supports WASM SIMD, and the
  // non-SIMD build is another 11 MB; without it the detector reports itself
  // unavailable and the studio falls back to fully manual marking.
  const names = ['vision_wasm_internal.js', 'vision_wasm_internal.wasm']
  if (names.every((n) => existsSync(path.join(dest, n)))) return 'cached'
  if (!existsSync(src)) return 'skipped (tasks-vision not installed)'
  await mkdir(dest, { recursive: true })
  for (const n of names) await cp(path.join(src, n), path.join(dest, n))
  return 'copied'
}

async function fetchModel(file, url) {
  const dest = path.join(pub, 'models', file)
  if ((await size(dest)) > 50_000) return 'cached'
  await mkdir(path.dirname(dest), { recursive: true })
  const res = await fetch(url)
  if (!res.ok) return `FAILED ${res.status}`
  await writeFile(dest, Buffer.from(await res.arrayBuffer()))
  return 'fetched'
}

// Self-hosted webfonts: pull the latin + latin-ext subsets so text renders
// identically offline and no request ever leaves the origin.
const FONTS = [
  ['Inter Tight', 'Inter+Tight:wght@300..800', 'inter-tight'],
  ['JetBrains Mono', 'JetBrains+Mono:wght@300..700', 'jetbrains-mono'],
  ['Instrument Serif', 'Instrument+Serif:ital@0;1', 'instrument-serif'],
]

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'

async function syncFonts() {
  const dest = path.join(pub, 'fonts')
  await mkdir(dest, { recursive: true })
  const faces = []
  let downloaded = 0
  for (const [family, spec, slug] of FONTS) {
    const css = await (await fetch(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, { headers: { 'User-Agent': UA } })).text()
    const blocks = css.split('@font-face').slice(1)
    for (const block of blocks) {
      const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] ?? ''
      const subset = /U\+0100-02BA/.test(range) ? 'latin-ext' : /U\+0000-00FF/.test(range) ? 'latin' : null
      if (!subset) continue
      const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
      const weight = block.match(/font-weight:\s*([^;]+);/)?.[1] ?? '400'
      const style = block.match(/font-style:\s*([^;]+);/)?.[1] ?? 'normal'
      if (!url) continue
      const file = style === 'italic' ? `${slug}-${subset}-italic.woff2` : `${slug}-${subset}.woff2`
      const out = path.join(dest, file)
      if (!(existsSync(out) && (await size(out)) > 1000)) {
        await writeFile(out, Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer()))
        downloaded += 1
      }
      faces.push({ family, weight, style, file, range })
    }
  }
  const css = [
    '/* Generated by scripts/setup-assets.mjs - do not edit by hand. */',
    ...faces.map(
      (f) =>
        `@font-face {\n  font-family: '${f.family}';\n  font-style: ${f.style};\n  font-weight: ${f.weight};\n  font-display: swap;\n  src: url('/fonts/${f.file}') format('woff2');\n  unicode-range: ${f.range};\n}`,
    ),
    '',
  ].join('\n')
  await writeFile(path.join(root, 'src/styles/fonts.css'), css)
  return `${faces.length} faces (${downloaded} downloaded)`
}

const wasmResult = await copyWasm()
const modelResults = []
for (const [file, url] of MODELS) modelResults.push(`${file}: ${await fetchModel(file, url)}`)
console.log(`[veil] mediapipe runtime: ${wasmResult}`)
console.log(`[veil] models: ${modelResults.join(', ')}`)
console.log(`[veil] fonts: ${await syncFonts()}`)
