"""Freeze reproducible property correlations and independent solver references.

Run: uv run --with thermo==0.6.0 python scripts/generate-properties.py
This is a build-time data generator. The published app has no Python dependency.
"""
import json
import math
from pathlib import Path

import thermo
from scipy.optimize import brentq
from thermo import Chemical, NRTL

assert thermo.__version__ == "0.6.0", "Property source version must stay pinned."
ROOT = Path(__file__).resolve().parents[1]
TREF = 298.15
TEMPERATURES = [280.0 + 2.0 * i for i in range(86)]
IDENTITIES = [
    ("ethanol", "64-17-5", "Ethanol", "C₂H₆O"),
    ("water", "7732-18-5", "Wasser", "H₂O"),
    ("benzene", "71-43-2", "Benzol", "C₆H₆"),
    ("toluene", "108-88-3", "Toluol", "C₇H₈"),
    ("hexane", "110-54-3", "n-Hexan", "C₆H₁₄"),
    ("heptane", "142-82-5", "n-Heptan", "C₇H₁₆"),
]
chemicals = {}
data = {
    "generator": "thermo 0.6.0",
    "referenceTemperature": TREF,
    "temperatureGrid": TEMPERATURES,
    "units": {"T": "K", "P": "Pa", "h": "J/mol", "cp": "J/(mol K)", "volume": "m³/mol"},
    "components": {},
}
references = {"pure": [], "nrtl": [], "bubble": []}

for key, cas, name, formula in IDENTITIES:
    c = Chemical(cas)
    chemicals[key] = c
    for property_name in ["VaporPressure", "HeatCapacityLiquid", "HeatCapacityGas", "VolumeLiquid", "EnthalpyVaporization"]:
        prop = getattr(c, property_name)
        assert "HEOS_FIT" in prop.all_methods, (key, property_name)
        prop.method = "HEOS_FIT"
    hl_tb = c.HeatCapacityLiquid.T_dependent_property_integral(TREF, c.Tb)
    hv_tb = hl_tb + c.EnthalpyVaporization(c.Tb)
    columns = {key: [] for key in ["logPsat", "dLogPsat", "hL", "cpL", "hV", "cpV", "vL", "dvL"]}
    for t in TEMPERATURES:
        values = {
            "logPsat": math.log(c.VaporPressure(t)),
            "dLogPsat": c.VaporPressure.T_dependent_property_derivative(t) / c.VaporPressure(t),
            "hL": c.HeatCapacityLiquid.T_dependent_property_integral(TREF, t),
            "cpL": c.HeatCapacityLiquid(t),
            "hV": hv_tb + c.HeatCapacityGas.T_dependent_property_integral(c.Tb, t),
            "cpV": c.HeatCapacityGas(t),
            "vL": c.VolumeLiquid.T_dependent_property(t),
            "dvL": c.VolumeLiquid.T_dependent_property_derivative(t),
        }
        for prop, value in values.items():
            assert math.isfinite(value), (key, prop, t)
            columns[prop].append(float(f"{value:.12g}"))
    data["components"][key] = {
        "name": name, "cas": cas, "formula": formula, "mw": c.MW / 1000,
        "boilingK": c.Tb, "criticalK": c.Tc,
        "methods": {p: getattr(c, p).method for p in ["VaporPressure", "HeatCapacityLiquid", "HeatCapacityGas", "VolumeLiquid", "EnthalpyVaporization"]},
        "source": f"https://webbook.nist.gov/cgi/cbook.cgi?ID=C{cas.replace('-', '')}&Mask=4",
        **columns,
    }
    for t in [301.17, 327.33, 350.15, 377.71, 419.45]:
        references["pure"].append({"id": key, "T": t, "p": c.VaporPressure(t), "hL": c.HeatCapacityLiquid.T_dependent_property_integral(TREF, t), "hV": hv_tb + c.HeatCapacityGas.T_dependent_property_integral(c.Tb, t), "cpL": c.HeatCapacityLiquid(t), "vL": c.VolumeLiquid.T_dependent_property(t)})

TAU_A = [[0, -0.8009], [3.4578, 0]]
TAU_B = [[0, 246.18], [-586.081, 0]]
ALPHA = [[0, 0.3], [0.3, 0]]


def nrtl(t, x):
    return NRTL(T=t, xs=[x, 1-x], tau_as=TAU_A, tau_bs=TAU_B, alpha_cs=ALPHA)


for t in [298.15, 325.13, 351.32, 372.95]:
    for x in [0.001, 0.05, 0.25, 0.5, 0.8, 0.95, 0.999]:
        obj = nrtl(t, x)
        references["nrtl"].append({"T": t, "x": x, "gamma": obj.gammas(), "hE": obj.HE()})

for system, a, b in [("ethanol-water", "ethanol", "water"), ("benzene-toluene", "benzene", "toluene"), ("hexane-heptane", "hexane", "heptane")]:
    for p in [70000, 101325, 150000]:
        for x in [0.02, 0.1, 0.3, 0.5, 0.8, 0.95]:
            def residual(t):
                gamma = nrtl(t, x).gammas() if system == "ethanol-water" else [1, 1]
                return x*gamma[0]*chemicals[a].VaporPressure(t) + (1-x)*gamma[1]*chemicals[b].VaporPressure(t) - p
            t = brentq(residual, 290, 420, xtol=1e-10)
            gamma = nrtl(t, x).gammas() if system == "ethanol-water" else [1, 1]
            y = x*gamma[0]*chemicals[a].VaporPressure(t)/p
            references["bubble"].append({"system": system, "P": p, "x": x, "T": t, "y": y})

# Generated numerical artifacts. Full precision reference numbers stay in tests.
(ROOT / "data").mkdir(exist_ok=True)
(ROOT / "tests").mkdir(exist_ok=True)
(ROOT / "data/properties.js").write_text("// Generated by scripts/generate-properties.py. See DATA.md.\nexport const PROPERTY_DATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
(ROOT / "tests/thermo-reference.json").write_text(json.dumps(references, indent=2) + "\n")
print(f"Frozen {len(IDENTITIES)} components × {len(TEMPERATURES)} temperatures × 8 properties.")
print(f"Reference cases: {len(references['pure'])} pure, {len(references['nrtl'])} NRTL, {len(references['bubble'])} bubble points.")
