'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, Plus, Check, Globe, Sun, Moon, Menu, X } from 'lucide-react';
import Content, { Footer } from './content';
import BackupDemo from './BackupDemo';
const base='https://preview.xenon.bot';
const invite='https://api.xenon.bot/auth/invite?return_origin=site&return_path=%2Finvited';
function Logo(){return <a className="logo" href="#" aria-label="Xenon home"><img className="logo-symbol" src="./logomark.svg" alt=""/>Xenon</a>}
function CTA({secondary=false}:{secondary?:boolean}){return <a className={secondary?'button secondary':'button primary'} href={secondary?base+'/templates':invite}>{secondary?'Explore templates':'Add to Discord'}{secondary?<ArrowUpRight size={18}/>:<Plus size={20}/>}</a>}
export default function Home(){const [light,setLight]=useState(false);const [menu,setMenu]=useState(false);return <div className={light?'site light':'site'}><header className="nav"><Logo/><nav className={menu?'navlinks open':'navlinks'}><a href="#features" onClick={()=>setMenu(false)}>Features <Plus size={12}/></a><a href="#templates" onClick={()=>setMenu(false)}>Templates</a><a href="#premium" onClick={()=>setMenu(false)}>Premium <span className="tiny-star">✳</span></a><a href={base+'/docs'}>Documentation <ArrowUpRight size={13}/></a></nav><div className="nav-actions"><details className="language"><summary aria-label="Select language"><Globe size={17}/><span>EN</span></summary><div><a href={base+'/'}>English</a><a href={base+'/de'}>Deutsch</a><a href={base+'/pt'}>Português</a></div></details><button className="icon-button" aria-label={light?'Use dark theme':'Use light theme'} onClick={()=>setLight(!light)}>{light?<Moon size={17}/>:<Sun size={17}/>}</button><a className="login" href="https://api.xenon.bot/auth/login?return_origin=site&return_path=%2F">Log in</a><a className="nav-cta" href={invite}>Add to Discord <ArrowUpRight size={16}/></a><button className="mobile-toggle icon-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header><main><section className="hero"><div className="hero-topline"><span><i className="live-dot"/> YOUR COMMUNITY. BUILT TO LAST.</span><a href="https://status.xenon.bot">System status <ArrowUpRight size={13}/></a></div><div className="hero-grid"><div className="hero-copy"><h1>Your server.<br/>Your rules.<br/><span>No regrets.</span></h1><div className="hero-description"><div className="little-cross">+</div><div><h2>Restore your Discord server in one command.</h2><p>Xenon saves your channels, roles and settings. With Premium it saves your messages, bans and role assignments too. Load a backup onto any server at any time, or start from one of thousands of free templates.</p></div></div><div className="hero-buttons"><CTA/><CTA secondary/></div><span className="hero-note"><Check size={14}/> Free to add. Ready in seconds.</span></div><BackupDemo/></div><div className="hero-footer"><span>LESS DAMAGE CONTROL. MORE COMMUNITY.</span><a href="#features">SCROLL TO EXPLORE ↓</a></div></section><div className="stats">{[['3.2M','servers protected'],['12M+','backups created'],['5k+','public templates'],['8 yrs','running since 2018'],['99.9%','uptime, 90 days']].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><Content/></main><Footer/></div>}
